<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1677654502015' stop='1677654514859'>
    <name>contact us tests</name>
    <title>contact us tests</title>
    <test-cases>
        <test-case start='1677654502015' status='failed' stop='1677654514857'>
            <name>successful submission - unique data</name>
            <title>successful submission - unique data</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: Angular could not be found on the page https://webdriveruniversity.com/Contact-Us/contactus.html. If this is not an Angular application, you may need to turn off waiting for Angular.
                                          Please see 
                                          https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load</message>
                <stack-trace>Error: Angular could not be found on the page https://webdriveruniversity.com/Contact-Us/contactus.html. If this is not an Angular application, you may need to turn off waiting for Angular.
                                          Please see 
                                          https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
                    at C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\built\browser.js:718:27
                    at ManagedPromise.invokeCallback_ (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27
                    at C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)
                From: Task: Run it("successful submission - unique data") in control flow
                    at UserContext.&lt;anonymous> (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
                    at attempt (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at QueueRunner.execute (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
                    at Spec.queueRunnerFactory (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
                    at Spec.execute (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
                    at UserContext.fn (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
                    at attempt (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at QueueRunner.execute (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\kvalmores\Desktop\Projects\ProtractorDemo\tests\contact_us.js:5:5)
                    at addSpecsToSuite (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\kvalmores\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\kvalmores\Desktop\Projects\ProtractorDemo\tests\contact_us.js:3:1)
                    at Module._compile (node:internal/modules/cjs/loader:1254:14)
                    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
                    at Module.load (node:internal/modules/cjs/loader:1117:32)
                    at Function.Module._load (node:internal/modules/cjs/loader:958:12)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>